### PR TITLE
Make stringprep an optional package

### PR DESCRIPTION
**Pull request by felixrieseberg**
According to the README, node-stringprep is optional. Package.json now supports optional dependencies - npm will try to install, but won't stop/exit the installation if building fails.

### CODE REVIEW

**Comment by sibartlett** [comment]
:+1:

**Comment by chris-rock** [comment]
+1

**Comment by lloydwatkin** [comment]
IIRC @dodo fixed the stringprep install so if it failed it didn't actually fail according to npm and we fell back to javascript equivalents? Is this correct @chris-rock, I think we still need stringprep module installed regardless.

**Comment by chris-rock** [comment]
yeah, it continues. I just saw some errors on io.js.

**Comment by sonnyp** [comment]
yes documentation is wrong, node-string-prep is required

**Pull request closed without merging**
