### PR TITLE
Emit event when sending raw data.

### PR DESCRIPTION
**Pull request by RobertLarsen**
This will somewhat fix https://github.com/node-xmpp/node-xmpp/issues/268
Component/Client/Server should pass the event on. I'll do that next if this PR is accepted.

### CODE REVIEW

**Comment by chris-rock** [comment]
@RobertLarsen thanks for contributing to node-xmpp. Could you please add a use case, why this should be added?

**Comment by RobertLarsen** [comment]
@chris-rock Of course.
I use the ejabberd server and it has traffic shaping rules. I need a way of knowing how much raw data is sent by my component and this allows me to graph it. So, only for statistics.

**Comment by chris-rock** [comment]
alright. got you. why not listening directly on the socket? is there any special need for listening on the connection?

**Comment by sonnyp** [comment]
@RobertLarsen you don't need this, you should monkey patch socket write like this:

var write = socket.write;
var total = 0;
socket.write = function(data) {
  write(data);
  total += new Buffer(data).length;
};

**Comment by RobertLarsen** [comment]
@sonnyp Right, that may actually be a better option.

**Comment by sonnyp** [comment]
@RobertLarsen I'm pretty sure there is a module out there to monitor a socket or stream, please let me know if you find/write one, I'm interested.

**Comment by chris-rock** [comment]
I recommend using socket.on('data', function(data){}). See https://nodejs.org/api/net.html#net_event_data

**Comment by sonnyp** [comment]
@chris-rock I think @RobertLarsen i interested in knowing how much is sent, not received.

**Comment by chris-rock** [comment]
ah you are right. Then you have two options:
1.) as @sonnyp proposed
2.) write your own log socket wrapper and log all data that comes through EventEmitter https://nodejs.org/api/events.html

**Pull request closed without merging**
