### PR TITLE
Rework JID parsing

### LINKED ISSUE #49: JID parsing incorrect
```javascript
> j = new jid('lloyd.watkin@somewhere/something@blah/ hello')
{ local: 'lloyd.watkin\\40somewhere\\2fsomething',
  domain: 'blah',
  resource: ' hello',
  user: 'lloyd.watkin\\40somewhere\\2fsomething' }
```

Should have resulted in:

```javascript
{ local: 'lloyd.watkin',
  domain: 'somewhere',
  resource: ' something@blah/ hello',
  user: 'lloyd.watkin' }
```

### PR DESCRIPTION
**Pull request by lloydwatkin**
Fixes #49

### CODE REVIEW

**Comment by chris-rock** [comment]
@lloydwatkin can we merge this?

**Comment by lloydwatkin** [comment]
I've kicked off a new build. If the tests pass then we should be good :)

**Comment by sonnyp** [comment]
@lloydwatkin is it still relevant?

Can I 'port' to node-xmpp/JID ?

**Comment by lloydwatkin** [comment]
I believe so, go for it. Great work on the library BTW!

**Comment by sonnyp** [comment]
@lloydwatkin thanks! mostly maintenance though I wish I had more time for features/tests/bug-fix

**Comment by lloydwatkin** [comment]
I know how you feel. Hopefully I'll be back to more fun stuff after the new year

**Comment by sonnyp** [comment]
fixed in https://github.com/node-xmpp/JID/pull/7

**Pull request closed without merging**
